import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

function ensureDir(path) {
  mkdirSync(path, { recursive: true });
}

function json(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function categoryTitle(category) {
  return {
    cli: "CLI",
    entrypoint: "Entrypoints",
    script: "Scripts",
    source: "Source",
    test: "Tests",
  }[category] ?? category;
}

function topHotspots(scan, limit = 8) {
  return Object.values(scan.impactMap.files)
    .filter(file => !file.path.startsWith("tests/") && !file.path.startsWith("test/"))
    .sort((left, right) => {
      if (left.riskRank !== right.riskRank) {
        const order = { critical: 3, high: 2, medium: 1, low: 0 };
        return order[right.riskRank] - order[left.riskRank];
      }
      return right.impactScore - left.impactScore;
    })
    .slice(0, limit);
}

function renderProjectCapsule(scan) {
  const hotspots = topHotspots(scan)
    .map(file => `- \`${file.path}\` — ${file.summary} (risk: ${file.riskRank}, importedBy: ${file.importedBy.length}, tests: ${file.nearbyTests.length})`)
    .join("\n") || "- No supported source files found.";

  const entrypoints = Object.values(scan.impactMap.files)
    .filter(file => file.category === "entrypoint" || file.category === "cli")
    .map(file => `- \`${file.path}\` — ${file.summary}`)
    .join("\n") || "- No obvious entrypoint found.";

  return `# Project Capsule

> Auto-generated by CapsuleMap.
> Project: \`${scan.repoName}\`
> Generated: ${scan.generatedAt}

## Project In One Sentence
- \`${scan.repoName}\` has ${scan.sourceFiles.length} source files and ${scan.testFiles.length} test files indexed for agent handoff.

## Scan Scope
- Source files: ${scan.sourceFiles.length}
- Test files: ${scan.testFiles.length}
- Total indexed files: ${scan.files.length}

## Entrypoints
${entrypoints}

## First Reads For Agents
- Architecture or onboarding: read this file and \`docs/ai/MODULE-INDEX.md\`.
- Code edits: read \`docs/ai/IMPACT-MAP.json\` for the changed file and \`docs/ai/TEST-MAP.json\` for likely tests.
- Review or refactor: also read \`docs/ai/ARCHITECTURE-LANGUAGE.md\` so terminology stays stable.

## Hotspots
${hotspots}

## Limits
- CapsuleMap preview is file-level. It does not provide symbol-level call graphs.
- Test suggestions are impact-aware hints, not a replacement for full test judgment.
`;
}

function renderModuleIndex(scan) {
  const groups = {};
  for (const file of Object.values(scan.impactMap.files)) {
    groups[file.category] ??= [];
    groups[file.category].push(file);
  }

  const sections = Object.entries(groups)
    .sort(([left], [right]) => categoryTitle(left).localeCompare(categoryTitle(right)))
    .map(([category, files]) => {
      const lines = files
        .sort((left, right) => left.path.localeCompare(right.path))
        .map(file => `- \`${file.path}\` — ${file.summary} | imports ${file.imports.length} | importedBy ${file.importedBy.length} | tests ${file.nearbyTests.length}`)
        .join("\n");
      return `## ${categoryTitle(category)}\n${lines}`;
    })
    .join("\n\n");

  return `# Module Index

> Auto-generated by CapsuleMap.
> Generated: ${scan.generatedAt}

${sections}
`;
}

function renderArchitectureLanguage(scan) {
  return `# Architecture Language

> Auto-generated by CapsuleMap.
> Project: \`${scan.repoName}\`

Use these words consistently when handing work to a coding agent.

## Handoff Pack
- The generated \`docs/ai/*\` files that summarize what to read, what may break, and what to test.

## Capsule
- A concise current-state summary. It should orient the next agent before it scans the whole repo.

## Impact Map
- File-level imports, reverse imports, nearby tests, and risk rank.

## Test Map
- Source-to-test and test-to-source relationships. Use it to pick focused tests before broad regression.

## Local Judge
- Optional local-model or heuristic triage. It can recommend reads and task type, but it is not the source of truth.

## Deletion Test
- If a module vanished, would complexity disappear or spread into callers? Good modules hide meaningful complexity.
`;
}

export function writeHandoffPack(scan, projectRoot = ".") {
  const root = resolve(projectRoot);
  const docsDir = join(root, "docs", "ai");
  ensureDir(docsDir);

  writeFileSync(join(docsDir, "PROJECT-CAPSULE.md"), renderProjectCapsule(scan));
  writeFileSync(join(docsDir, "MODULE-INDEX.md"), renderModuleIndex(scan));
  writeFileSync(join(docsDir, "ARCHITECTURE-LANGUAGE.md"), renderArchitectureLanguage(scan));
  writeFileSync(join(docsDir, "IMPACT-MAP.json"), json(scan.impactMap));
  writeFileSync(join(docsDir, "TEST-MAP.json"), json(scan.testMap));

  return {
    docsDir,
    files: [
      "PROJECT-CAPSULE.md",
      "MODULE-INDEX.md",
      "ARCHITECTURE-LANGUAGE.md",
      "IMPACT-MAP.json",
      "TEST-MAP.json",
    ].map(file => join(docsDir, file)),
  };
}

export function renderHandoffPrompt(projectRoot = ".") {
  const root = resolve(projectRoot);
  const capsulePath = join(root, "docs", "ai", "PROJECT-CAPSULE.md");
  const modulePath = join(root, "docs", "ai", "MODULE-INDEX.md");
  if (!existsSync(capsulePath) || !existsSync(modulePath)) {
    throw new Error("Missing docs/ai handoff pack. Run `capsulemap init .` first.");
  }

  const capsule = readFileSync(capsulePath, "utf8");
  const firstLines = capsule
    .split(/\r?\n/)
    .slice(0, 36)
    .join("\n");

  return `You are taking over this repository.

Read these files before editing:
- docs/ai/PROJECT-CAPSULE.md
- docs/ai/MODULE-INDEX.md
- docs/ai/IMPACT-MAP.json for every file you plan to modify
- docs/ai/TEST-MAP.json before choosing tests

Current capsule excerpt:

${firstLines}
`;
}
