import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

function ensureDir(path) {
  mkdirSync(path, { recursive: true });
}

function json(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function categoryTitle(category) {
  return {
    cli: "CLI",
    entrypoint: "Entrypoints",
    script: "Scripts",
    source: "Source",
    test: "Tests",
  }[category] ?? category;
}

function topHotspots(scan, limit = 8) {
  return Object.values(scan.impactMap.files)
    .filter(file => !file.path.startsWith("tests/") && !file.path.startsWith("test/"))
    .sort((left, right) => {
      if (left.riskRank !== right.riskRank) {
        const order = { critical: 3, high: 2, medium: 1, low: 0 };
        return order[right.riskRank] - order[left.riskRank];
      }
      return right.impactScore - left.impactScore;
    })
    .slice(0, limit);
}

function renderProjectCapsule(scan) {
  const hotspots = topHotspots(scan)
    .map(file => `- \`${file.path}\` — ${file.summary} (risk: ${file.riskRank}, importedBy: ${file.importedBy.length}, tests: ${file.nearbyTests.length})`)
    .join("\n") || "- No supported source files found.";

  const entrypoints = Object.values(scan.impactMap.files)
    .filter(file => file.category === "entrypoint" || file.category === "cli")
    .map(file => `- \`${file.path}\` — ${file.summary}`)
    .join("\n") || "- No obvious entrypoint found.";

  return `# Project Capsule

> Auto-generated by CapsuleMap.
> Project: \`${scan.repoName}\`
> Generated: ${scan.generatedAt}

## Project In One Sentence
- \`${scan.repoName}\` has ${scan.sourceFiles.length} source files and ${scan.testFiles.length} test files indexed for agent handoff.

## Scan Scope
- Source files: ${scan.sourceFiles.length}
- Test files: ${scan.testFiles.length}
- Total indexed files: ${scan.files.length}

## Entrypoints
${entrypoints}

## First Reads For Agents
- Architecture or onboarding: read this file and \`docs/ai/MODULE-INDEX.md\`.
- Code edits: read \`docs/ai/IMPACT-MAP.json\` for the changed file and \`docs/ai/TEST-MAP.json\` for likely tests.
- Known function/class/type name: run \`capsulemap symbol <name-or-regex> .\` instead of reading broad files.
- Review or refactor: also read \`docs/ai/ARCHITECTURE-LANGUAGE.md\` so terminology stays stable.

## Hotspots
${hotspots}

## Limits
- CapsuleMap includes a definition-level symbol index. It does not provide symbol-level call graphs.
- Test suggestions are impact-aware hints, not a replacement for full test judgment.
`;
}

function renderModuleIndex(scan) {
  const groups = {};
  for (const file of Object.values(scan.impactMap.files)) {
    groups[file.category] ??= [];
    groups[file.category].push(file);
  }

  const sections = Object.entries(groups)
    .sort(([left], [right]) => categoryTitle(left).localeCompare(categoryTitle(right)))
    .map(([category, files]) => {
      const lines = files
        .sort((left, right) => left.path.localeCompare(right.path))
        .map(file => `- \`${file.path}\` — ${file.summary} | imports ${file.imports.length} | importedBy ${file.importedBy.length} | tests ${file.nearbyTests.length}`)
        .join("\n");
      return `## ${categoryTitle(category)}\n${lines}`;
    })
    .join("\n\n");

  return `# Module Index

> Auto-generated by CapsuleMap.
> Generated: ${scan.generatedAt}

${sections}
`;
}

function renderArchitectureLanguage(scan) {
  return `# Architecture Language

> Auto-generated by CapsuleMap.
> Project: \`${scan.repoName}\`

Use these words consistently when handing work to a coding agent.

## Handoff Pack
- The generated \`docs/ai/*\` files that summarize what to read, what may break, and what to test.

## Capsule
- A concise current-state summary. It should orient the next agent before it scans the whole repo.

## Impact Map
- File-level imports, reverse imports, nearby tests, and risk rank.

## Symbol Map
- Definition-level functions, classes, interfaces, types, enums, and exported constants. It helps agents find where a name lives without claiming full call-graph precision.

## Test Map
- Source-to-test and test-to-source relationships. Use it to pick focused tests before broad regression.

## Local Judge
- Optional local-model or heuristic triage. It can recommend reads and task type, but it is not the source of truth.

## Attention Gate
- A rule that limits what an agent reads or injects for the current task. More context is not automatically better.

## Deletion Test
- If a module vanished, would complexity disappear or spread into callers? Good modules hide meaningful complexity.
`;
}

function renderSymbolIndex(scan) {
  const symbols = Object.values(scan.symbolMap.symbols)
    .sort((left, right) => left.path.localeCompare(right.path) || left.line - right.line || left.name.localeCompare(right.name));
  const exported = symbols.filter(symbol => symbol.exported).slice(0, 120);
  const byFile = Object.entries(scan.symbolMap.byFile)
    .sort(([left], [right]) => left.localeCompare(right));

  const quickList = exported.length
    ? exported.map(symbol => `- \`${symbol.name}\` (${symbol.kind}) — \`${symbol.path}:${symbol.line}\``).join("\n")
    : "- No exported symbols found.";
  const fileCounts = byFile.length
    ? byFile.map(([path, ids]) => {
        const exportedCount = ids
          .map(id => scan.symbolMap.symbols[id])
          .filter(Boolean)
          .filter(symbol => symbol.exported)
          .length;
        return `- \`${path}\` — ${ids.length} symbols, ${exportedCount} exported`;
      }).join("\n")
    : "- No symbols found.";

  return `# Symbol Index

> Auto-generated by CapsuleMap.
> Project: \`${scan.repoName}\`
> Symbols: ${symbols.length}

## How To Use
- Find a definition: \`capsulemap symbol <name-or-regex> .\`
- List definitions in a file: \`capsulemap symbols <path> .\`
- Do not paste all of \`SYMBOL-MAP.json\` into an agent context. It is a query artifact.

## Exported Quick List
${quickList}${exported.length === 120 ? "\n- ... more exported symbols available through `capsulemap symbol <name-or-regex> .`" : ""}

## File Counts
${fileCounts}
`;
}

export function renderSearchGraphRoadmap(scan) {
  return `# Local Search & Graph Roadmap

> Auto-generated by CapsuleMap.
> Project: \`${scan.repoName}\`

CapsuleMap starts with repo-native handoff maps, but it is shaped by a practical agent workflow that combines local markdown search, relationship graphs, and strict attention budgeting.

This file is intentionally a roadmap, not a hidden dependency list. The current release does not bundle QMD, a vector database, or a memory graph runtime. It records the public integration contract so teams can add those layers without turning the handoff pack into an opaque memory service.

## Battle-Tested Origin

The workflow behind this roadmap uses three separate layers:

- **Local markdown search** finds likely relevant notes, docs, and handoff files.
- **Relationship graphs** explain why decisions, modules, tests, and lessons are connected.
- **Attention gates** decide how much of that context should be shown to the next agent.

CapsuleMap 0.1 makes the first layer of that workflow portable: a small file-level handoff pack that any repository can review and version.

## Search Adapter

A future search adapter should answer: "Which documents are probably relevant to this task?"

Recommended shape:

- Support plain keyword search for exact names, file paths, commands, and error strings.
- Support vector search for semantic matches across wording and language.
- Fuse keyword and vector candidates with a deterministic ranker such as RRF.
- Keep query expansion and reranking measurable instead of always-on.
- Record benchmark fixtures so model or index changes can be compared.

A concrete local-search setup that informed this roadmap:

- **Base tool**: QMD-style local markdown search.
- **Keyword index**: SQLite FTS5 with a trigram tokenizer for CJK-friendly substring search.
- **Embedding model**: \`multilingual-e5-large-instruct\`, selected over smaller multilingual experiments when recall and score separation mattered.
- **Query mode**: hybrid keyword + vector retrieval.
- **Fusion**: deterministic RRF-style score fusion.
- **Short CJK fallback**: very short Chinese queries need vector or alternate matching because trigram matching naturally starts at 3 characters.

## Relationship Graph Adapter

A future graph adapter should answer: "Why are these files, decisions, tests, or lessons connected?"

Recommended shape:

- Treat search results as candidates, not final context.
- Add relation facts such as imports, reverse imports, ownership, decision links, test links, and known lessons.
- Keep graph facts short and inspectable.
- Prefer local files or SQLite-style storage before hosted services.
- Make graph output optional per task; architecture review needs it more than a one-line typo fix.

CapsuleMap already includes a file-level impact map. A graph adapter should extend that map rather than replace it.

## Attention Gate

The hardest part is not finding more context. It is deciding what not to inject.

Recommended shape:

- Start with \`PROJECT-CAPSULE.md\` and \`MODULE-INDEX.md\`.
- Add \`IMPACT-MAP.json\` and \`TEST-MAP.json\` only for files likely to be edited.
- Add search hits only when the capsule is missing or too thin.
- Add graph facts only when the task asks about relationships, causes, architecture, or risk.
- Cap injected results, dedupe repeated documents, and keep raw history out of the default path.

This keeps agents fast because they start from a map instead of rereading the whole repo or drowning in unrelated memory.

## Integration Contract

Adapters should be able to plug into CapsuleMap without changing its core contract:

1. The handoff pack stays in \`docs/ai/*\`.
2. Every generated artifact is readable by humans.
3. Search explains where to look.
4. Graph explains why things connect.
5. Attention gates decide what is worth reading now.
6. The agent still verifies against source code before editing.

## Not Included Yet

- Bundled QMD integration.
- Built-in vector index.
- Built-in relationship graph database.
- Symbol-level call graph.
- MCP server.
- Hosted memory backend.
`;
}

export function writeHandoffPack(scan, projectRoot = ".") {
  const root = resolve(projectRoot);
  const docsDir = join(root, "docs", "ai");
  ensureDir(docsDir);

  writeFileSync(join(docsDir, "PROJECT-CAPSULE.md"), renderProjectCapsule(scan));
  writeFileSync(join(docsDir, "MODULE-INDEX.md"), renderModuleIndex(scan));
  writeFileSync(join(docsDir, "SYMBOL-INDEX.md"), renderSymbolIndex(scan));
  writeFileSync(join(docsDir, "ARCHITECTURE-LANGUAGE.md"), renderArchitectureLanguage(scan));
  writeFileSync(join(docsDir, "SEARCH-GRAPH-ROADMAP.md"), renderSearchGraphRoadmap(scan));
  writeFileSync(join(docsDir, "IMPACT-MAP.json"), json(scan.impactMap));
  writeFileSync(join(docsDir, "SYMBOL-MAP.json"), json(scan.symbolMap));
  writeFileSync(join(docsDir, "TEST-MAP.json"), json(scan.testMap));

  return {
    docsDir,
    files: [
      "PROJECT-CAPSULE.md",
      "MODULE-INDEX.md",
      "SYMBOL-INDEX.md",
      "ARCHITECTURE-LANGUAGE.md",
      "SEARCH-GRAPH-ROADMAP.md",
      "IMPACT-MAP.json",
      "SYMBOL-MAP.json",
      "TEST-MAP.json",
    ].map(file => join(docsDir, file)),
  };
}

export function renderHandoffPrompt(projectRoot = ".") {
  const root = resolve(projectRoot);
  const capsulePath = join(root, "docs", "ai", "PROJECT-CAPSULE.md");
  const modulePath = join(root, "docs", "ai", "MODULE-INDEX.md");
  if (!existsSync(capsulePath) || !existsSync(modulePath)) {
    throw new Error("Missing docs/ai handoff pack. Run `capsulemap init .` first.");
  }

  const capsule = readFileSync(capsulePath, "utf8");
  const firstLines = capsule
    .split(/\r?\n/)
    .slice(0, 36)
    .join("\n");

  return `You are taking over this repository.

Read these files before editing:
- docs/ai/PROJECT-CAPSULE.md
- docs/ai/MODULE-INDEX.md
- docs/ai/IMPACT-MAP.json for every file you plan to modify
- docs/ai/TEST-MAP.json before choosing tests
- docs/ai/SEARCH-GRAPH-ROADMAP.md when the task involves search, memory, graph, retrieval, or context injection

Current capsule excerpt:

${firstLines}
`;
}
